// <auto-generated />
using MShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MShop.Migrations
{
    [DbContext(typeof(MShopDbContext))]
    [Migration("20210404190531_SeedDataMigTables")]
    partial class SeedDataMigTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MShop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "مردانه",
                            Name = "لباس مردانه"
                        },
                        new
                        {
                            Id = 2,
                            Description = "زنانه",
                            Name = "لباس زنانه"
                        },
                        new
                        {
                            Id = 3,
                            Description = "بچگانه",
                            Name = "لباس بچگانه"
                        });
                });

            modelBuilder.Entity("MShop.Models.CategoryToProdact", b =>
                {
                    b.Property<int>("ProdactId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("ProdactId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryToProdacts");
                });

            modelBuilder.Entity("MShop.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("MShop.Models.Prodact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("Prodacts");
                });

            modelBuilder.Entity("MShop.Models.CategoryToProdact", b =>
                {
                    b.HasOne("MShop.Models.Category", "Category")
                        .WithMany("CategoryToProdacts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MShop.Models.Prodact", "Prodact")
                        .WithMany("CategoryToProdacts")
                        .HasForeignKey("ProdactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Prodact");
                });

            modelBuilder.Entity("MShop.Models.Prodact", b =>
                {
                    b.HasOne("MShop.Models.Item", "Item")
                        .WithOne("Prodact")
                        .HasForeignKey("MShop.Models.Prodact", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("MShop.Models.Category", b =>
                {
                    b.Navigation("CategoryToProdacts");
                });

            modelBuilder.Entity("MShop.Models.Item", b =>
                {
                    b.Navigation("Prodact");
                });

            modelBuilder.Entity("MShop.Models.Prodact", b =>
                {
                    b.Navigation("CategoryToProdacts");
                });
#pragma warning restore 612, 618
        }
    }
}
